// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoleMaster.Infrastructure.Data;

#nullable disable

namespace RoleMaster.Infrastructure.Migrations
{
    [DbContext(typeof(RoleMasterDbContext))]
    partial class RoleMasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoleMaster.Core.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Acrobacia")
                        .HasColumnType("integer");

                    b.Property<string>("AliadosEOrganizacoes")
                        .HasColumnType("text");

                    b.Property<string>("Alinhamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Altura")
                        .HasColumnType("text");

                    b.Property<string>("Antecedente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AparenciaDoPersonagem")
                        .HasColumnType("text");

                    b.Property<int>("Arcanismo")
                        .HasColumnType("integer");

                    b.Property<int>("Atletismo")
                        .HasColumnType("integer");

                    b.Property<int>("Atuacao")
                        .HasColumnType("integer");

                    b.Property<int>("BonusProficiencia")
                        .HasColumnType("integer");

                    b.Property<string>("CaracteristicasETalentos")
                        .HasColumnType("text");

                    b.Property<int>("Carisma")
                        .HasColumnType("integer");

                    b.Property<int>("ChaMod")
                        .HasColumnType("integer");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClasseArmadura")
                        .HasColumnType("integer");

                    b.Property<int>("ConMod")
                        .HasColumnType("integer");

                    b.Property<int>("Constituicao")
                        .HasColumnType("integer");

                    b.Property<string>("CorDaPele")
                        .HasColumnType("text");

                    b.Property<string>("CorDoCabelo")
                        .HasColumnType("text");

                    b.Property<string>("CorDosOlhos")
                        .HasColumnType("text");

                    b.Property<string>("DadoDeVida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Deslocamento")
                        .HasColumnType("integer");

                    b.Property<int>("Destreza")
                        .HasColumnType("integer");

                    b.Property<int>("DexMod")
                        .HasColumnType("integer");

                    b.Property<int>("Enganacao")
                        .HasColumnType("integer");

                    b.Property<int>("Forca")
                        .HasColumnType("integer");

                    b.Property<string>("Fraquezas")
                        .HasColumnType("text");

                    b.Property<int>("Furtividade")
                        .HasColumnType("integer");

                    b.Property<int>("Historia")
                        .HasColumnType("integer");

                    b.Property<string>("HistoriaDoPersonagem")
                        .HasColumnType("text");

                    b.Property<int?>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Ideais")
                        .HasColumnType("text");

                    b.Property<int>("Iniciativa")
                        .HasColumnType("integer");

                    b.Property<int>("Inspiracao")
                        .HasColumnType("integer");

                    b.Property<int>("IntMod")
                        .HasColumnType("integer");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("integer");

                    b.Property<int>("Intimidacao")
                        .HasColumnType("integer");

                    b.Property<int>("Intuicao")
                        .HasColumnType("integer");

                    b.Property<int>("Investigacao")
                        .HasColumnType("integer");

                    b.Property<int>("LidarComAnimais")
                        .HasColumnType("integer");

                    b.Property<int>("Medicina")
                        .HasColumnType("integer");

                    b.Property<int>("Natureza")
                        .HasColumnType("integer");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeDoJogador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutrasProficienciasEIdiomas")
                        .HasColumnType("text");

                    b.Property<int>("Percepcao")
                        .HasColumnType("integer");

                    b.Property<int>("Persuasao")
                        .HasColumnType("integer");

                    b.Property<string>("Peso")
                        .HasColumnType("text");

                    b.Property<int>("PontosDeExperiencia")
                        .HasColumnType("integer");

                    b.Property<int>("PontosDeVidaAtuais")
                        .HasColumnType("integer");

                    b.Property<int>("PontosDeVidaMaximos")
                        .HasColumnType("integer");

                    b.Property<int>("PontosDeVidaTemporarios")
                        .HasColumnType("integer");

                    b.Property<int>("Prestidigitacao")
                        .HasColumnType("integer");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Religiao")
                        .HasColumnType("integer");

                    b.Property<int>("Sabedoria")
                        .HasColumnType("integer");

                    b.Property<int>("SabedoriaPassivaPercepcao")
                        .HasColumnType("integer");

                    b.Property<bool>("SalvaGuardaCarisma")
                        .HasColumnType("boolean");

                    b.Property<bool>("SalvaGuardaConstituicao")
                        .HasColumnType("boolean");

                    b.Property<bool>("SalvaGuardaDestreza")
                        .HasColumnType("boolean");

                    b.Property<bool>("SalvaGuardaForca")
                        .HasColumnType("boolean");

                    b.Property<bool>("SalvaGuardaInteligencia")
                        .HasColumnType("boolean");

                    b.Property<bool>("SalvaGuardaSabedoria")
                        .HasColumnType("boolean");

                    b.Property<int>("SalvaguardaMorteFalhas")
                        .HasColumnType("integer");

                    b.Property<int>("SalvaguardaMorteSucessos")
                        .HasColumnType("integer");

                    b.Property<int>("Sobrevivencia")
                        .HasColumnType("integer");

                    b.Property<int>("StrMod")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("Tesouros")
                        .HasColumnType("text");

                    b.Property<string>("TracosDePersonalidade")
                        .HasColumnType("text");

                    b.Property<string>("Vinculos")
                        .HasColumnType("text");

                    b.Property<int>("WisMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("RoleMaster.Core.Entities.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("RoleMaster.Core.Entities.Magia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Magias");
                });

            modelBuilder.Entity("RoleMaster.Core.Entities.Equipamento", b =>
                {
                    b.HasOne("RoleMaster.Core.Entities.Character", null)
                        .WithMany("Equipamento")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("RoleMaster.Core.Entities.Magia", b =>
                {
                    b.HasOne("RoleMaster.Core.Entities.Character", null)
                        .WithMany("Magia")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("RoleMaster.Core.Entities.Character", b =>
                {
                    b.Navigation("Equipamento");

                    b.Navigation("Magia");
                });
#pragma warning restore 612, 618
        }
    }
}
